language: node_js
node_js:
  - 10
cache:
  directories:
    - ~/.npm
    - node_modules
install:
  - yarn install
before_script:
  - yarn start -- --silent &
script:
  - yarn run test -- -u
  - yarn run cypress:run