version: '2'
services:
    web:
        image: onitsoft/nginx:node
        volumes:
            - /nexchange/etc/letsencrypt:/etc/letsencrypt
            - /nexchange/etc/nginx/ssl:/etc/nginx/ssl
            - /nexchange/etc/nginx/nginx.conf:/etc/nginx/nginx.conf
            - /nexchange/etc/nginx/.htpasswd:/etc/nginx/.htpasswd
            - /nexchange/root:/nexchange/root
        ports:
            - "8000:80"
            - "8443:443"
        restart: always
    react-client:
        image: onitsoft/nexchange-open-client-react
        volumes:
            - /nexchange/root/nexchange:/deploy/app/build
    ico-page:
        image: onitsoft/ico-landing-page
        volumes:
            - /nexchange/root/ico:/deploy/app/build
    fed-proxy:
        image: onitsoft/nexchange-fed-proxy
        volumes:
            - /nexchange/root:/deploy
        ports:
            - "3000:3000"
            
